In [93]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import math

In [94]:
df=pd.read_csv('round1.csv')

In [95]:
df.head()
print(df['Category'].unique())
print(df['Quota'].unique())
df['Quota'].replace(to_replace='AP',value='HS',inplace=True)
df['Quota'].replace(to_replace='GO',value='HS',inplace=True)

['General' 'General PwD' 'EWS' 'OBC-NCL' 'OBC-NCL(PwD)' 'SC' 'SC PwD' 'ST'
 'ST PwD' 'EWS PwD' 'GEN-EWS' 'OPEN' 'OPEN (PwD)' 'SC (PwD)'
 'GEN-EWS(PwD)' 'ST (PwD)' 'OBC-\r\nNCL(PwD)' 'GEN-\r\nEWS(PwD)'
 'OBC- NCL(PwD)' 'GEN- EWS(PwD)']
['AI' 'AP' 'GO' 'HS' 'OS']

In [96]:
df['Category'].replace(to_replace='General',value='GEN',inplace=True)
df['Category'].replace(to_replace='General PwD',value='GEN-PwD',inplace=True)
df['Category'].replace(to_replace='OBC-NCL(PwD)',value='OBC-NCL-PwD',inplace=True)
df['Category'].replace(to_replace='SC PwD',value='SC-PwD',inplace=True)
df['Category'].replace(to_replace='EWS PwD',value='EWS-PwD',inplace=True)
df['Category'].replace(to_replace='ST PwD',value='ST-PwD',inplace=True)
df['Category'].replace(to_replace='GEN-EWS',value='EWS',inplace=True)
df['Category'].replace(to_replace='SC (PwD)',value='SC-PwD',inplace=True)
df['Category'].replace(to_replace='SC PwD',value='SC-PwD',inplace=True)
df['Category'].replace(to_replace='GEN-EWS(PwD)',value='EWS-PwD',inplace=True)
df['Category'].replace(to_replace='ST (PwD)',value='ST-PwD',inplace=True)
df['Category'].replace(to_replace='OBC-\nNCL(PwD)',value='OBC-NCL-PwD',inplace=True)
df['Category'].replace(to_replace='GEN-\nEWS(PwD)',value='EWS-PwD',inplace=True)
df['Category'].replace(to_replace='OBC- NCL(PwD)',value='OBC-NCL-PwD',inplace=True)
df['Category'].replace(to_replace='GEN- EWS(PwD)',value='EWS-PwD',inplace=True)
df['Category'].replace(to_replace='OPEN (PwD)',value='OPEN-PwD',inplace=True)

In [97]:
df['Category'].unique()

array(['GEN', 'GEN-PwD', 'EWS', 'OBC-NCL', 'OBC-NCL-PwD', 'SC', 'SC-PwD',
       'ST', 'ST-PwD', 'EWS-PwD', 'OPEN', 'OPEN-PwD', 'OBC-\r\nNCL(PwD)',
       'GEN-\r\nEWS(PwD)'], dtype=object)

In [98]:
df.head()

,Round\r\nNo,Institute,Branch Name,Quota,Category,Seat Pool,Opening Rank,Closing Rank
0,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,GEN,Gender-Neutral,7536.0,9403
1,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,GEN-PwD,Gender-Neutral,264.0,264
2,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,EWS,Gender-Neutral,1072.0,1172
3,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL,Gender-Neutral,2716.0,3677
4,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL-PwD,Gender-Neutral,124.0,124

In [99]:
df.rename(columns={'Round\nNo': 'Round No', 'Opening\nRank': 'Opening Rank','Round\r\nNo':'Round No'},inplace=True)

In [100]:
df.head()

,Round No,Institute,Branch Name,Quota,Category,Seat Pool,Opening Rank,Closing Rank
0,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,GEN,Gender-Neutral,7536.0,9403
1,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,GEN-PwD,Gender-Neutral,264.0,264
2,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,EWS,Gender-Neutral,1072.0,1172
3,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL,Gender-Neutral,2716.0,3677
4,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL-PwD,Gender-Neutral,124.0,124

In [101]:
print(df['Institute'].unique())
len(df['Institute'].unique())

['Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior'
 'Indian Institute of Information Technology (IIIT)Kota,\r\nRajasthan'
 'Indian Institute of Information Technology Guwahati'
 'Indian Institute of Information Technology(IIIT)\r\nKalyani, West Bengal'
 'Indian Institute of Information Technology(IIIT)\r\nKilohrad, Sonepat, Haryana'
 'Indian Institute of Information Technology(IIIT) Una,\r\nHimachal Pradesh'
 'Indian Institute of Information Technology (IIIT), Sri\r\nCity, Chittoor'
 'Indian Institute of Information Technology(IIIT),\r\nVadodara, Gujrat'
 'Indian Institute of Information Technology, Allahabad'
 'Indian Institute of Information Technology, Design &\r\nManufacturing, Kancheepuram'
 'Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram'
 'Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture\r\nJabalpur'
 'Pt. Dwarka Prasad Mishra Indian Institute of\r\nInformation Technology, Design & Manufacture Jabalpur'
 'Indian Institute of Information Technology  Manipur'
 'Indian Institute of Information Technology Srirangam,\r\nTiruchirappalli'
 'Indian Institute of Information Technology Lucknow'
 'Indian Institute of Information Technology(IIIT)\r\nDharwad'
 'Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh'
 'Indian Institute of Information Technology(IIIT)\r\nKottayam'
 'Indian Institute of Information Technology (IIIT) Ranchi'
 'Indian Institute of Information Technology (IIIT)\r\nNagpur'
 'Indian Institute of Information Technology (IIIT) Pune'
 'Indian Institute of Information Technology Bhagalpur'
 'Indian Institute of Information Technology Bhopal'
 'Indian Institute of Information Technology Surat'
 'Indian Institute of Information Technology, Agartala'
 'Indian institute of information technology, Raichur,\r\nKarnataka'
 'Assam University, Silchar' 'Gurukula Kangri Vishwavidyalaya, Haridwar'
 'Indian Institute of Carpet Technology,  Bhadohi'
 'Institute of Infrastructure, Technology, Research and\r\nManagement-Ahmedabad'
 'Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)'
 'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad'
 'National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)'
 'National Institute of Foundry & Forge Technology,\r\nHatia, Ranchi'
 'Sant Longowal Institute of Engineering and\r\nTechnology'
 'Mizoram University, Aizawl'
 'School of Engineering, Tezpur University, Napaam,\r\nTezpur'
 'School of Planning & Architecture, Bhopal'
 'School of Planning & Architecture, New Delhi'
 'School of Planning & Architecture: Vijayawada'
 'Shri Mata Vaishno Devi University, Katra, Jammu &\r\nKashmir'
 'HNB Garhwal University Srinagar (Garhwal)'
 'International Institute of Information Technology,\r\nNaya Raipur'
 'University of Hyderabad' 'Jawaharlal Nehru University, Delhi'
 'International Institute of Information Technology,\r\nBhubaneswar'
 'Central institute of Technology Kokrajar, Assam'
 'Pondicherry Engineering College, Puducherry'
 'Central University of Rajasthan, Rajasthan'
 'National Institute of Food Technology\r\nEntrepreneurship and Management, Sonepat, Haryana'
 'National Institute of Food Technology Entrepreneurship and Management, Sonepat,\r\nHaryana'
 'National Institute of Technology, Warangal'
 'National Institute of Technology Goa'
 'Dr. B R Ambedkar National Institute of Technology,\r\nJalandhar'
 'Malaviya National Institute of Technology Jaipur'
 'Maulana Azad National Institute of Technology Bhopal'
 'Motilal Nehru National Institute of Technology\r\nAllahabad'
 'National Institute of Technology  Agartala'
 'National Institute of Technology Calicut'
 'National Institute of Technology Delhi'
 'National Institute of Technology Durgapur'
 'National Institute of Technology Hamirpur'
 'National Institute of Technology Karnataka, Surathkal'
 'National Institute of Technology Meghalaya'
 'National Institute of Technology Nagaland'
 'National Institute of Technology Patna'
 'National Institute of Technology Puducherry'
 'National Institute of Technology Raipur'
 'National Institute of Technology Sikkim'
 'National Institute of Technology Arunachal Pradesh'
 'National Institute of Technology, Jamshedpur'
 'National Institute of Technology, Kurukshetra'
 'National Institute of Technology, Manipur'
 'National Institute of Technology, Mizoram'
 'National Institute of Technology, Rourkela'
 'National Institute of Technology, Silchar'
 'National Institute of Technology, Srinagar'
 'National Institute of Technology, Tiruchirappalli'
 'National Institute of Technology, Uttarakhand'
 'Sardar Vallabhbhai National Institute of Technology,\r\nSurat'
 'Visvesvaraya National Institute of Technology, Nagpur'
 'National Institute of Technology, Andhra Pradesh'
 'Birla Institute of Technology, Mesra,  Ranchi'
 'Indian Institute of Engineering Science and\r\nTechnology, Shibpur'
 'Punjab Engineering College, Chandigarh'
 'Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal'
 'Motilal Nehru National Institute of Technology Allahabad'
 'Sardar Vallabhbhai National Institute of Technology, Surat'
 'Indian Institute of Information Technology(IIIT) Kalyani,\r\nWest Bengal'
 'Indian Institute of Information Technology(IIIT) Kilohrad,\r\nSonepat, Haryana'
 'Indian Institute of Information Technology (IIIT), Sri City,\r\nChittoor'
 'Indian Institute of Information Technology(IIIT), Vadodara,\r\nGujrat'
 'Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur'
 'Indian Institute of Information Technology(IIIT) Dharwad'
 'Indian Institute of Information Technology(IIIT) Kottayam'
 'Indian Institute of Information Technology (IIIT) Nagpur'
 'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad-\r\nAllahabad'
 'J.K. Institute of Applied Physics & Technology, Department\r\nof Electronics & Communication, University of Allahabad- Allahabad'
 'National Institute of Foundry & Forge Technology, Hatia,\r\nRanchi'
 'Sant Longowal Institute of Engineering and Technology'
 'School of Engineering, Tezpur University, Napaam, Tezpur'
 'Indian Institute of Engineering Science and Technology,\r\nShibpur'
 'International Institute of Information Technology, Naya\r\nRaipur'
 'Ghani Khan Choudhary Institute of Engineering and\r\nTechnology, Malda, West Bengal'
 'National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana'
 'Pt. Dwarka Prasad Mishra Indian Institute of\r\nInformation Technology, Design & Manufacture\r\nJabalpur'
 'Indian Institute of Information Technology (IIIT)\r\nRanchi'
 'J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication,\r\nUniversity of Allahabad- Allahabad'
 'Maulana Azad National Institute of Technology\r\nBhopal'
 'Visvesvaraya National Institute of Technology,\r\nNagpur'
 'Institute of Technology, Guru Ghasidas\r\nVishwavidyalaya (A Central University), Bilaspur, (C.G.)'
 'J.K. Institute of Applied Physics & Technology,\r\nDepartment of Electronics & Communication, University of Allahabad- Allahabad']

113

In [102]:
df['Institute'].replace(to_replace='Maulana Azad National Institute of Technology\nBhopal',value='NIT Bhopal',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT) Una,\nHimachal Pradesh',value='IIIT Una',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT), Sri\nCity, Chittoor',value='IIIT Sri City',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT),\nVadodara, Gujrat',value='IIIT Vadodara',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology, Allahabad',value='IIIT Allahabad',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology, Design &\nManufacturing, Kancheepuram',value='IIIT-DM Kancheepuram',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram',value='IIIT-DM Kancheepuram',inplace=True)
df['Institute'].replace(to_replace='Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture\nJabalpur',value='IIIT-DM Jabalpur',inplace=True)
df['Institute'].replace(to_replace='Pt. Dwarka Prasad Mishra Indian Institute of\nInformation Technology, Design & Manufacture Jabalpur',value='IIIT-DM Jabalpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology  Manipur',value='IIIT Manipur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Srirangam,\nTiruchirappalli',value='IIIT Tiruchirappalli',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT)\nDharwad',value='IIIT Dharwad',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh',value='IIIT-DM Kurnool',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT)\nKottayam',value='IIIT Kottayam',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT) Ranchi',value='IIIT Ranchi',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT)\nNagpur',value='IIIT Nagpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT) Pune',value='IIIT Pune',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology, Agartala',value='IIIT Agartala',inplace=True)
df['Institute'].replace(to_replace='Indian institute of information technology, Raichur,\nKarnataka',value='IIIT Raichur',inplace=True)
df['Institute'].replace(to_replace='Institute of Infrastructure, Technology, Research and\nManagement-Ahmedabad',value='Institute of Infrastructure Technology Research and Management,Ahmedabad',inplace=True)
df['Institute'].replace(to_replace='Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)',value='Institute of Technology, Guru Ghasidas Vishwavidyalaya,Bilaspur,(C.G.)',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication, University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)',value='National Institute of Electronics and Information Technology, Aurangabad,Maharashtra',inplace=True)
df['Institute'].replace(to_replace='National Institute of Foundry & Forge Technology,\nHatia, Ranchi',value='National Institute of Foundry & Forge Technology,Hatia,Ranchi',inplace=True)
df['Institute'].replace(to_replace='Sant Longowal Institute of Engineering and\nTechnology',value='Sant Longowal Institute of Engineering and Technology',inplace=True)
df['Institute'].replace(to_replace='School of Engineering, Tezpur University, Napaam,\nTezpur',value='School of Engineering,Tezpur University,Napaam,Tezpur',inplace=True)
df['Institute'].replace(to_replace='School of Planning & Architecture: Vijayawada',value='School of Planning & Architecture,Vijayawada',inplace=True)
df['Institute'].replace(to_replace='Shri Mata Vaishno Devi University, Katra, Jammu &\nKashmir',value='Shri Mata Vaishno Devi University,Katra,Jammu & Kashmir',inplace=True)
df['Institute'].replace(to_replace='HNB Garhwal University Srinagar (Garhwal)',value='HNB Garhwal University Srinagar Garhwal',inplace=True)
df['Institute'].replace(to_replace='International Institute of Information Technology,\nNaya Raipur',value='IIIT Naya Raipur',inplace=True)
df['Institute'].replace(to_replace='International Institute of Information Technology,\nBhubaneswar',value='IIIT Bhubaneswar',inplace=True)
df['Institute'].replace(to_replace='National Institute of Food Technology\nEntrepreneurship and Management, Sonepat, Haryana',value='National Institute of Food Technology Entrepreneurship and Management,Sonepat,Haryana',inplace=True)
df['Institute'].replace(to_replace='National Institute of Food Technology Entrepreneurship and Management, Sonepat,\nHaryana',value='National Institute of Food Technology Entrepreneurship and Management,Sonepat,Haryana',inplace=True)

In [103]:
df['Institute'].replace(to_replace='Dr. B R Ambedkar National Institute of Technology,\nJalandhar',value='NITMJalandhar',inplace=True)
df['Institute'].replace(to_replace='Motilal Nehru National Institute of Technology\nAllahabad',value='NIT Allahabad',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Karnataka, Surathkal',value='NIT Surathkal',inplace=True)
df['Institute'].replace(to_replace='Sardar Vallabhbhai National Institute of Technology,\nSurat',value='NIT Surat',inplace=True)
df['Institute'].replace(to_replace='Birla Institute of Technology, Mesra,  Ranchi',value='BITS Mesra',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Engineering Science and\nTechnology, Shibpur',value='Indian Institute of Engineering Science and Technology, Shibpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT) Kalyani,\nWest Bengal',value='IIIT Kalyani',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT) Kilohrad,\nSonepat, Haryana',value='IIIT Sonepat',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT), Sri City,\nChittoor',value='IIIT Sri City',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT), Vadodara,\nGujrat',value='IIIT Vadodara',inplace=True)
df['Institute'].replace(to_replace='Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur',value='IIIT-DM Jabalpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT) Dharwad',value='IIIT Dharwad',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT) Kottayam',value='IIIT Kottayam',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT) Nagpur',value='IIIT Nagpur',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad-\nAllahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication, University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology, Department\nof Electronics & Communication, University of Allahabad- Allahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication, University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='National Institute of Foundry & Forge Technology, Hatia,\nRanchi',value='National Institute of Foundry & Forge Technology,Hatia,Ranchi',inplace=True)
df['Institute'].replace(to_replace='School of Engineering, Tezpur University, Napaam, Tezpur',value='School of Engineering,Tezpur University,Napaam,Tezpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Engineering Science and Technology,\nShibpur',value='Indian Institute of Engineering Science and Technology, Shibpur',inplace=True)
df['Institute'].replace(to_replace='International Institute of Information Technology, Naya\nRaipur',value='IIIT Naya Raipur',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology,\nDepartment of Electronics & Communication, University of Allahabad- Allahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication, University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication,\nUniversity of Allahabad- Allahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication, University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='Institute of Technology, Guru Ghasidas\nVishwavidyalaya (A Central University), Bilaspur, (C.G.)',value='Institute of Technology, Guru Ghasidas Vishwavidyalaya,Bilaspur,(C.G.)',inplace=True)
df['Institute'].replace(to_replace='Visvesvaraya National Institute of Technology,\nNagpur',value='NIT Nagpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT)\nRanchi',value='IIIT Ranchi',inplace=True)
df['Institute'].replace(to_replace='Pt. Dwarka Prasad Mishra Indian Institute of\nInformation Technology, Design & Manufacture\nJabalpur',value='IIIT-DM Jabalpur',inplace=True)
df['Institute'].replace(to_replace='National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana',value='National Institute of Food Technology Entrepreneurship and Management,Sonepat',inplace=True)
df['Institute'].replace(to_replace='Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal',value='Ghani Khan Choudhary Institute of Engineering and Technology,Malda',inplace=True)
df['Institute'].replace(to_replace='Visvesvaraya National Institute of Technology, Nagpur',value='NIT Nagpur',inplace=True)
df['Institute'].replace(to_replace='Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal',value='Ghani Khan Choudhary Institute of Engineering and Technology,Malda',inplace=True)
df['Institute'].replace(to_replace='Sardar Vallabhbhai National Institute of Technology, Surat',value='NIT Surat',inplace=True)
df['Institute'].replace(to_replace='Ghani Khan Choudhary Institute of Engineering and\nTechnology, Malda, West Bengal',value='Ghani Khan Choudhary Institute of Engineering and Technology,Malda',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT)Kota,\nRajasthan',value='IIIT Kota',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT)\nKalyani, West Bengal',value='IIIT Kalyani',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT)\nKilohrad, Sonepat, Haryana',value='IIIT Sonepat',inplace=True)
df['Institute'].replace(to_replace='Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior',value='IIIT-M Gwalior',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT)Kota,\r\nRajasthan',value='IIIT Kota',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Guwahati',value='IIIT Guwahati',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT)\r\nKalyani, West Bengal',value='IIIT Kalyani',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT) Una,\r\nHimachal Pradesh',value='IIIT Una',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT)\r\nKilohrad, Sonepat, Haryana',value='IIIT Sonepat',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT), Sri\r\nCity, Chittoor',value='IIIT Sri City',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT),\r\nVadodara, Gujrat',value='IIIT Vadodara',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology, Design &\r\nManufacturing, Kancheepuram',value='IIIT-DM Kancheepuram',inplace=True)
df['Institute'].replace(to_replace='Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture\r\nJabalpur',value='IIIT-DM Jabalpur',inplace=True)
df['Institute'].replace(to_replace='Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior',value='IIIT-M Gwalior',inplace=True)
df['Institute'].replace(to_replace='Pt. Dwarka Prasad Mishra Indian Institute of\r\nInformation Technology, Design & Manufacture Jabalpur',value='IIIT-DM Jabalpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Srirangam,\r\nTiruchirappalli',value='IIIT Tiruchirappalli',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Lucknow',value='IIIT Lucknow',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT)\r\nDharwad',value='IIIT Dharwad',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT)\r\nKottayam',value='IIIT Kottayam',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT)\r\nNagpur',value='IIIT Nagpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Bhagalpur',value='IIIT Bhagalpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Bhopal',value='IIIT Bhopal',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Surat',value='IIIT Surat',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology Bhopal',value='IIIT Bhopal',inplace=True)
df['Institute'].replace(to_replace='Indian institute of information technology, Raichur,\r\nKarnataka',value='IIIT Raichur',inplace=True)
df['Institute'].replace(to_replace='Institute of Infrastructure, Technology, Research and\r\nManagement-Ahmedabad',value='Institute of Infrastructure Technology Research and Management,Ahmedabad',inplace=True)
df['Institute'].replace(to_replace='National Institute of Foundry & Forge Technology,\r\nHatia, Ranchi',value='National Institute of Foundry & Forge Technology,Ranchi',inplace=True)
df['Institute'].replace(to_replace='Sant Longowal Institute of Engineering and\r\nTechnology',value='Sant Longowal Institute of Engineering and Technology',inplace=True)
df['Institute'].replace(to_replace='School of Engineering, Tezpur University, Napaam,\r\nTezpur',value='School of Engineering,Tezpur University,Tezpur',inplace=True)
df['Institute'].replace(to_replace='Shri Mata Vaishno Devi University, Katra, Jammu &\r\nKashmir',value='Shri Mata Vaishno Devi University,Jammu & Kashmir',inplace=True)
df['Institute'].replace(to_replace='International Institute of Information Technology,\r\nNaya Raipur',value='IIIT Naya Raipur',inplace=True)
df['Institute'].replace(to_replace='International Institute of Information Technology,\r\nBhubaneswar',value='IIIT Bhubaneswar',inplace=True)
df['Institute'].replace(to_replace='National Institute of Food Technology\r\nEntrepreneurship and Management, Sonepat, Haryana',value='National Institute of Food Technology Entrepreneurship and Management,Sonepat',inplace=True)
df['Institute'].replace(to_replace='National Institute of Food Technology Entrepreneurship and Management, Sonepat,\r\nHaryana',value='National Institute of Food Technology Entrepreneurship and Management,Sonepat',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Warangal',value='NIT Warangal',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Goa',value='NIT Goa',inplace=True)
df['Institute'].replace(to_replace='Dr. B R Ambedkar National Institute of Technology,\r\nJalandhar',value='NIT Jalandhar',inplace=True)
df['Institute'].replace(to_replace='Malaviya National Institute of Technology Jaipur',value='NIT Jaipur',inplace=True)
df['Institute'].replace(to_replace='Maulana Azad National Institute of Technology Bhopal',value='NIT Bhopal',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology  Agartala',value='NIT Agartala',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Calicut',value='NIT Calicut',inplace=True)
df['Institute'].replace(to_replace='Motilal Nehru National Institute of Technology\r\nAllahabad',value='NIT Allahabad',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Delhi',value='NIT Delhi',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Durgapur',value='NIT Durgapur',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Hamirpur',value='NIT Hamirpur',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Meghalaya',value='NIT Meghalaya',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Nagaland',value='NIT Nagaland',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Patna',value='NIT Patna',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Puducherry',value='NIT Puducherry',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Raipur',value='NIT Raipur',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Sikkim',value='NIT Sikkim',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology Arunachal Pradesh',value='NIT Arunachal Pradesh',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Jamshedpur',value='NIT Jameshdpur',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Kurukshetra',value='NIT Kurukshetra',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Manipur',value='NIT Manipur',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Mizoram',value='NIT Mizoram',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Rourkela',value='NIT Rourkela',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Silchar',value='NIT Silchar',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Srinagar',value='NIT Srinagar',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Tiruchirappalli',value='NIT Tiruchirappalli',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Uttarakhand',value='NIT Uttrakhand',inplace=True)
df['Institute'].replace(to_replace='Sardar Vallabhbhai National Institute of Technology,\r\nSurat',value='NIT Surat',inplace=True)
df['Institute'].replace(to_replace='National Institute of Technology, Andhra Pradesh',value='NIT Andhra Pradesh',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Engineering Science and\r\nTechnology, Shibpur',value='Indian Institute of Engineering Science and Technology,Shibpur',inplace=True)
df['Institute'].replace(to_replace='Motilal Nehru National Institute of Technology Allahabad',value='NIT Allahabad',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT) Kalyani,\r\nWest Bengal',value='IIIT Kalyani',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT) Kilohrad,\r\nSonepat, Haryana',value='IIIT Sonepat',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT), Sri City,\r\nChittoor',value='IIIT Sri City',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology(IIIT), Vadodara,\r\nGujrat',value='IIIT Vadodara',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad-\r\nAllahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication,University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology, Department\r\nof Electronics & Communication, University of Allahabad- Allahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication,University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='National Institute of Foundry & Forge Technology, Hatia,\r\nRanchi',value='National Institute of Foundry & Forge Technology,Ranchi',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Engineering Science and Technology,\r\nShibpur',value='Indian Institute of Engineering Science and Technology,Shibpur',inplace=True)
df['Institute'].replace(to_replace='International Institute of Information Technology, Naya\r\nRaipur',value='IIIT Naya Raipur',inplace=True)
df['Institute'].replace(to_replace='Ghani Khan Choudhary Institute of Engineering and\r\nTechnology, Malda, West Bengal',value='Ghani Khan Choudhary Institute of Engineering and Technology,West Bengal',inplace=True)
df['Institute'].replace(to_replace='Pt. Dwarka Prasad Mishra Indian Institute of\r\nInformation Technology, Design & Manufacture\r\nJabalpur',value='IIIT-DM Jabalpur',inplace=True)
df['Institute'].replace(to_replace='Indian Institute of Information Technology (IIIT)\r\nRanchi',value='IIIT Ranchi',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication,\r\nUniversity of Allahabad- Allahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication,University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='Maulana Azad National Institute of Technology\r\nBhopal',value='NIT Bhopal',inplace=True)
df['Institute'].replace(to_replace='Visvesvaraya National Institute of Technology,\r\nNagpur',value='NIT Nagpur',inplace=True)
df['Institute'].replace(to_replace='Institute of Technology, Guru Ghasidas\r\nVishwavidyalaya (A Central University), Bilaspur, (C.G.)',value='Institute of Technology,Guru Ghasidas Vishwavidyalaya,Bilaspur,(C.G.)',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology,\r\nDepartment of Electronics & Communication, University of Allahabad- Allahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication,University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='Ghani Khan Choudhary Institute of Engineering and Technology,Malda',value='Ghani Khan Choudhary Institute of Engineering and Technology,West Bengal',inplace=True)
df['Institute'].replace(to_replace='Institute of Technology, Guru Ghasidas Vishwavidyalaya,Bilaspur,(C.G.)',value='Institute of Technology,Guru Ghasidas Vishwavidyalaya,Bilaspur,(C.G.)',inplace=True)
df['Institute'].replace(to_replace='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication, University of Allahabad',value='J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication,University of Allahabad',inplace=True)
df['Institute'].replace(to_replace='School of Engineering,Tezpur University,Napaam,Tezpur',value='School of Engineering,Tezpur University,Tezpur',inplace=True)
df['Institute'].replace(to_replace='NIT Meghalya',value='NIT Meghalaya',inplace=True)

In [104]:
print(df['Institute'].unique())
len(df['Institute'].unique())

['IIIT-M Gwalior' 'IIIT Kota' 'IIIT Guwahati' 'IIIT Kalyani'
 'IIIT Sonepat' 'IIIT Una' 'IIIT Sri City' 'IIIT Vadodara'
 'IIIT Allahabad' 'IIIT-DM Kancheepuram' 'IIIT-DM Jabalpur' 'IIIT Manipur'
 'IIIT Tiruchirappalli' 'IIIT Lucknow' 'IIIT Dharwad' 'IIIT-DM Kurnool'
 'IIIT Kottayam' 'IIIT Ranchi' 'IIIT Nagpur' 'IIIT Pune' 'IIIT Bhagalpur'
 'IIIT Bhopal' 'IIIT Surat' 'IIIT Agartala' 'IIIT Raichur'
 'Assam University, Silchar' 'Gurukula Kangri Vishwavidyalaya, Haridwar'
 'Indian Institute of Carpet Technology,  Bhadohi'
 'Institute of Infrastructure Technology Research and Management,Ahmedabad'
 'Institute of Technology,Guru Ghasidas Vishwavidyalaya,Bilaspur,(C.G.)'
 'J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication,University of Allahabad'
 'National Institute of Electronics and Information Technology, Aurangabad,Maharashtra'
 'National Institute of Foundry & Forge Technology,Ranchi'
 'Sant Longowal Institute of Engineering and Technology'
 'Mizoram University, Aizawl'
 'School of Engineering,Tezpur University,Tezpur'
 'School of Planning & Architecture, Bhopal'
 'School of Planning & Architecture, New Delhi'
 'School of Planning & Architecture,Vijayawada'
 'Shri Mata Vaishno Devi University,Jammu & Kashmir'
 'HNB Garhwal University Srinagar Garhwal' 'IIIT Naya Raipur'
 'University of Hyderabad' 'Jawaharlal Nehru University, Delhi'
 'IIIT Bhubaneswar' 'Central institute of Technology Kokrajar, Assam'
 'Pondicherry Engineering College, Puducherry'
 'Central University of Rajasthan, Rajasthan'
 'National Institute of Food Technology Entrepreneurship and Management,Sonepat'
 'NIT Warangal' 'NIT Goa' 'NIT Jalandhar' 'NIT Jaipur' 'NIT Bhopal'
 'NIT Allahabad' 'NIT Agartala' 'NIT Calicut' 'NIT Delhi' 'NIT Durgapur'
 'NIT Hamirpur' 'NIT Surathkal' 'NIT Meghalaya' 'NIT Nagaland' 'NIT Patna'
 'NIT Puducherry' 'NIT Raipur' 'NIT Sikkim' 'NIT Arunachal Pradesh'
 'NIT Jameshdpur' 'NIT Kurukshetra' 'NIT Manipur' 'NIT Mizoram'
 'NIT Rourkela' 'NIT Silchar' 'NIT Srinagar' 'NIT Tiruchirappalli'
 'NIT Uttrakhand' 'NIT Surat' 'NIT Nagpur' 'NIT Andhra Pradesh'
 'BITS Mesra'
 'Indian Institute of Engineering Science and Technology,Shibpur'
 'Punjab Engineering College, Chandigarh'
 'Ghani Khan Choudhary Institute of Engineering and Technology,West Bengal']

84

In [105]:
state=[]

In [106]:
def set_value(row_number, assigned_value): 
    return assigned_value[row_number] 
state={'Assam University, Silchar' : 'Assam', 
       'NIT Tiruchirappalli' : 'Tamil Nadu', 
       'NIT Surat' : 'Gujarat',
       'IIIT-M Gwalior':'All India',
      'IIIT Kota':'All India',
       'IIIT Guwahati':'All India',
       'IIIT Kalyani':'All India',
       'IIIT Sonepat':'All India',
       'IIIT Una':'All India',
       'IIIT Sri City':'All India',
       'IIIT Vadodara':'All India',
       'IIIT Allahabad':'All India',
       'IIIT-DM Kancheepuram':'All India',
       'IIIT-DM Jabalpur':'All India',
       'IIIT Manipur':'All India',
       'IIIT Tiruchirappalli':'All India',
       'IIIT Lucknow':'All India',
       'IIIT Dharwad':'All India',
       'IIIT-DM Kurnool':'All India',
       'IIIT Kottayam':'All India',
       'IIIT Ranchi':'All India',
       'IIIT Nagpur':'All India',
       'IIIT Pune':'All India',
       'IIIT Bhagalpur':'All India',
       'IIIT Bhopal':'All India',
       'IIIT Surat':'All India',
       'IIIT Agartala':'All India',
       'IIIT Raichur':'All India',
       'Gurukula Kangri Vishwavidyalaya, Haridwar':'All India',
      'Institute of Technology,Guru Ghasidas Vishwavidyalaya,Bilaspur,(C.G.)':'All India',
       'J.K. Institute of Applied Physics & Technology,Department of Electronics & Communication,University of Allahabad':'All India',
      'Indian Institute of Carpet Technology,  Bhadohi':'All India',
       'National Institute of Electronics and Information Technology, Aurangabad,Maharashtra':'All India',
      'National Institute of Foundry & Forge Technology,Ranchi':'All India',
       'Sant Longowal Institute of Engineering and Technology':'All India',
       'Mizoram University, Aizawl':'All India',
       'School of Engineering,Tezpur University,Tezpur':'All India',
       'School of Planning & Architecture, Bhopal':'All India',
       'School of Planning & Architecture, New Delhi':'All India',
       'School of Planning & Architecture,Vijayawada':'All India',
       'Shri Mata Vaishno Devi University,Jammu & Kashmir':'All India',
       'HNB Garhwal University Srinagar Garhwal':'All India',
       'IIIT Naya Raipur':'All India',
       'University of Hyderabad':'All India',
       'Jawaharlal Nehru University, Delhi':'All India',
       'IIIT Bhubaneswar':'All India',
       'Central institute of Technology Kokrajar, Assam':'All India',
       'Pondicherry Engineering College, Puducherry':'All India',
       'Central University of Rajasthan, Rajasthan':'All India',
       'National Institute of Food Technology Entrepreneurship and Management,Sonepat':'All India',
      'NIT Warangal':'Andhra Pradesh',
       'NIT Goa':'Goa',
       'NIT Jalandhar':'Punjab',
       'NIT Jaipur':'Rajashtahn',
       'NIT Bhopal':'Madhya Pradesh',
       'NIT Allahabad':'Uttar Pradesh',
       'NIT Agartala':'Tripura',
       'NIT Calicut':'Kerela',
       'NIT Delhi':'Delhi',
       'NIT Durgapur':'West Bengal',
       'NIT Hamirpur':'Himachal Pradesh',
       'NIT Surathkal':'Karnataka',
       'NIT Meghalaya':'Meghalaya',
       'NIT Nagaland':'Nagaland',
       'NIT Patna':'Bihar',
       'NIT Puducherry':'Puducherry',
       'NIT Raipur':'Chattisgarh',
       'NIT Sikkim':'Sikkim',
       'NIT Arunachal Pradesh':'Arunachal Pradesh',
       'NIT Jamshedpur':'Jharkhand',
       'NIT Kurukshetra':'Haryana',
       'NIT Manipur':'Manipur',
       'NIT Mizoram':'Mizoram',
       'NIT Rourkela':'Odhisa',
       'NIT Silchar':'Assam',
       'NIT Srinagar':'Jammu and Kahmir',
       'NIT Tiruchirappalli':'Tamil Nadu',
       'NIT Uttrakhand':'Uttarakhand',
       'NIT Surat':'Gujarat',
       'NIT Nagpur':'Maharashtra',
       'NIT Andhra Pradesh':'Andhra Pradesh',
       'BITS Mesra':'Jharkhand',
       'Indian Institute of Engineering Science and Technology,Shibpur':'West Bengal',
       'Punjab Engineering College, Chandigarh':'Punjab',
       'Ghani Khan Choudhary Institute of Engineering and Technology,West Bengal':'West Bengal',
       'Institute of Infrastructure Technology Research and Management,Ahmedabad':'All India',
       'NIT Jameshdpur':'Jharkhand'
      } 
df['State'] = df['Institute'].apply(set_value, args =(state, ))
df.head(50)

,Round No,Institute,Branch Name,Quota,Category,Seat Pool,Opening Rank,Closing Rank,State
0,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,GEN,Gender-Neutral,7536.0,9403,All India
1,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,GEN-PwD,Gender-Neutral,264.0,264,All India
2,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,EWS,Gender-Neutral,1072.0,1172,All India
3,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL,Gender-Neutral,2716.0,3677,All India
4,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL-PwD,Gender-Neutral,124.0,124,All India
5,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,SC,Gender-Neutral,1470.0,2344,All India
6,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,SC-PwD,Gender-Neutral,15.0,15,All India
7,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,ST,Gender-Neutral,1025.0,1506,All India
8,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,GEN,Female-Only,10308.0,12834,All India
9,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL,Female-Only,6780.0,7333,All India
10,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,SC,Female-Only,2994.0,2994,All India
11,1,IIIT-M Gwalior,"Computer Science and Engineering(4 year, Bache...",AI,ST,Female-Only,2325.0,2325,All India
12,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,GEN,Gender-Neutral,9713.0,14442,All India
13,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,GEN-PwD,Gender-Neutral,347.0,467,All India
14,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,EWS,Gender-Neutral,1716.0,1916,All India
15,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,OBC-NCL,Gender-Neutral,3834.0,6326,All India
16,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,OBC-NCL-PwD,Gender-Neutral,477.0,477,All India
17,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,SC,Gender-Neutral,2883.0,4380,All India
18,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,ST,Gender-Neutral,1930.0,2891,All India
19,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,ST-PwD,Gender-Neutral,17.0,17,All India
20,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,GEN,Female-Only,14037.0,18926,All India
21,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,OBC-NCL,Female-Only,7762.0,9945,All India
22,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,SC,Female-Only,4882.0,5050,All India
23,1,IIIT-M Gwalior,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,ST,Female-Only,3924.0,3924,All India
24,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,GEN,Gender-Neutral,7028.0,17896,All India
25,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,GEN-PwD,Gender-Neutral,558.0,558,All India
26,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,EWS,Gender-Neutral,2198.0,2218,All India
27,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,OBC-NCL,Gender-Neutral,4737.0,7903,All India
28,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,OBC-NCL-PwD,Gender-Neutral,478.0,478,All India
29,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,SC,Gender-Neutral,4441.0,5566,All India
30,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,ST,Gender-Neutral,2933.0,3127,All India
31,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,GEN,Female-Only,19501.0,23610,All India
32,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,OBC-NCL,Female-Only,10712.0,11150,All India
33,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,SC,Female-Only,6489.0,6489,All India
34,1,IIIT-M Gwalior,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,ST,Female-Only,4254.0,4254,All India
35,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,GEN,Gender-Neutral,10952.0,18446,All India
36,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,GEN-PwD,Gender-Neutral,681.0,716,All India
37,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,EWS,Gender-Neutral,2290.0,2790,All India
38,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,EWS-PwD,Gender-Neutral,69.0,69,All India
39,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL,Gender-Neutral,5165.0,7947,All India
40,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,OBC-NCL-PwD,Gender-Neutral,421.0,528,All India
41,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,SC,Gender-Neutral,2024.0,4127,All India
42,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,SC-PwD,Gender-Neutral,160.0,160,All India
43,1,IIIT Kota,"Computer Science and Engineering(4 year, Bache...",AI,ST,Gender-Neutral,1307.0,2350,All India
44,1,IIIT Kota,Electronics and Communication Engineering(4 ye...,AI,GEN,Gender-Neutral,16843.0,23339,All India
45,1,IIIT Kota,Electronics and Communication Engineering(4 ye...,AI,GEN-PwD,Gender-Neutral,1245.0,1245,All India
46,1,IIIT Kota,Electronics and Communication Engineering(4 ye...,AI,EWS,Gender-Neutral,2966.0,3279,All India
47,1,IIIT Kota,Electronics and Communication Engineering(4 ye...,AI,OBC-NCL,Gender-Neutral,7970.0,9760,All India
48,1,IIIT Kota,Electronics and Communication Engineering(4 ye...,AI,OBC-NCL-PwD,Gender-Neutral,532.0,532,All India
49,1,IIIT Kota,Electronics and Communication Engineering(4 ye...,AI,SC,Gender-Neutral,4370.0,5459,All India

In [107]:
#Data Cleaning ends

In [108]:
df.tail()
print(df.dtypes)
df['Closing Rank']=df['Closing Rank'].astype(int)

Round No          int64
Institute        object
Branch Name      object
Quota            object
Category         object
Seat Pool        object
Opening Rank    float64
Closing Rank      int64
State            object
dtype: object

In [109]:
df.to_csv(r'round1_cleaned.csv', index = False)

In [18]:
def final2(rank,category,state,gender,pwd):
    if(pwd=='YES'):
        if(gender=='M'):
            catg=category+'-PwD'
            p=df[(df['Closing Rank']>=rank)&((df['Category']==catg)|(df['Category']=='OPEN-PwD'))&(df['Seat Pool']=='Gender-Neutral')]
        else:
            catg=category+'-PwD'
            p=df[(df['Closing Rank']>=rank)&((df['Category']==catg)|(df['Category']=='OPEN-PwD'))]
    else:
        if(gender=='M'):
            p=df[(df['Closing Rank']>=rank)&((df['Category']==category)|(df['Category']=='OPEN'))&(df['Seat Pool']=='Gender-Neutral')]
        else:
             p=df[(df['Closing Rank']>=rank)&((df['Category']==category)|(df['Category']=='OPEN'))]  
    return p

In [19]:
df2=final2(1311,'GEN','Andhra Pradesh','M','NO')
s='Andhra Pradesh'
k=[]
for i in df2.index:
    if(df2['State'][i]==s):
        if(df2['Quota'][i]=='OS'):
            k.append(i)
    elif((df2['State'][i]!='All India')&(df2['State'][i]!=s)):
        if(df2['Quota'][i]=='HS'):
            k.append(i)
q=df2.drop(index=k)
q

,Round No,Institute,Branch Name,Quota,Category,Seat Pool,Opening Rank,Closing Rank,State
0,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Computer Science and Engineering(4 year, Bache...",AI,GEN,Gender-Neutral,7536.0,9403,All India
12,1,Atal Bihari Vajpayee Indian Institute of Infor...,Integrated B. Tech.(IT) and M. Tech (IT)(5 yea...,AI,GEN,Gender-Neutral,9713.0,14442,All India
24,1,Atal Bihari Vajpayee Indian Institute of Infor...,"Integrated B. Tech.(IT) and MBA(5 year, Integr...",AI,GEN,Gender-Neutral,7028.0,17896,All India
35,1,Indian Institute of Information Technology Kot...,"Computer Science and Engineering(4 year, Bache...",AI,GEN,Gender-Neutral,10952.0,18446,All India
44,1,Indian Institute of Information Technology Kot...,Electronics and Communication Engineering(4 ye...,AI,GEN,Gender-Neutral,16843.0,23339,All India
...,...,...,...,...,...,...,...,...,...
41992,7,Ghani Khan Choudhary Institute of Engineering ...,"Mechanical Engineering (4 Years, Bachelor of T...",OS,OPEN,Gender-Neutral,43813.0,54000,West Bengal
42000,7,Ghani Khan Choudhary Institute of Engineering ...,"Food Technology (4 Years, Bachelor of Technology)",OS,OPEN,Gender-Neutral,57749.0,60548,West Bengal
42005,7,"Central University of Rajasthan, Rajasthan","Computer Science and Engineering (4 Years, Bac...",AI,OPEN,Gender-Neutral,22306.0,34395,All India
42010,7,"Central University of Rajasthan, Rajasthan",Electronics and Communication Engineering (4 Y...,AI,OPEN,Gender-Neutral,30728.0,39824,All India
42015,7,National Institute of Food Technology Entrepre...,"Food Technology and Management (4 Years, Bache...",AI,OPEN,Gender-Neutral,21170.0,61228,All India

In [ ]:
#RANK TO PERCENTILE

In [112]:
rvp=pd.read_csv('rankVperc.csv')
print(rvp.head())
rvp['RANK']=rvp['RANK'].astype(int)
rvp.dtypes

  CATEGORY  RANK  PERCENTILE
0  GENERAL    13     100.000
1  GENERAL    34      99.999
2  GENERAL    53      99.998
3  GENERAL    69      99.997
4  GENERAL    80      99.996

CATEGORY       object
RANK            int32
PERCENTILE    float64
dtype: object

In [113]:
rvp['CATEGORY'].replace(to_replace='OBC',value='OBC-NCL',inplace=True)
rvp['CATEGORY'].replace(to_replace='OBC-PWD',value='OBC-NCL-PwD',inplace=True)
rvp['CATEGORY'].replace(to_replace='GENERAL',value='GEN',inplace=True)
rvp['CATEGORY'].replace(to_replace='GENERAL-PWD',value='GEN-PwD',inplace=True)
rvp['CATEGORY'].replace(to_replace='SC-PWD',value='SC-PwD',inplace=True)
rvp['CATEGORY'].replace(to_replace='ST-PWD',value='ST-PwD',inplace=True)
rvp['CATEGORY'].unique()

array(['GEN', 'EWS', 'OBC-NCL', 'SC', 'ST', 'GEN-PwD', 'EWS-PWD',
       'OBC-NCL-PwD', 'SC-PwD', 'ST-PwD'], dtype=object)

In [115]:
rvp.to_csv(r'rvp_cleaned.csv', index = False)